{{- if and .Values.global.networkPolicyEnabled .Values.prometheusOperator.admissionWebhooks.enabled .Values.prometheusOperator.admissionWebhooks.patch.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "prometheus-operator.admission.fullname" . }}
  labels: {{ include "labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  podSelector:
    matchLabels: {{ include "labels" . | nindent 6 }}
  policyTypes:
  - Egress
  egress:
  - {}
{{- end }}
