{{- if and .Values.kubeEtcd.enabled (not .Values.endpointController.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "kube-etcd.fullname" . }}
  labels: {{ include "kube-etcd.labels" . | nindent 4 }}
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: {{ .Values.kubeEtcd.service.port }}
      protocol: TCP
      targetPort: {{ .Values.kubeEtcd.service.targetPort }}
{{- if .Values.kubeEtcd.endpoints }}{{- else }}
  selector:
    {{- if .Values.kubeEtcd.service.selector }}
{{ toYaml .Values.kubeEtcd.service.selector | indent 4 }}
    {{- else}}
    component: etcd
    {{- end}}
{{- end }}
  type: ClusterIP
{{- end -}}
