---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aoi-grafana-datasources
  namespace: {{ .Release.Namespace }}
  labels:
    aoi_grafana_datasource: "1"
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
    - name: VictoriaMetrics
      uid: victoriametrics
      type: prometheus
      url: {{ include "aoi.grafanaReadUrl" . }}
      access: proxy
      isDefault: true
      jsonData:
        oauthPassThru: true
