{{- if .Values.grafana.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/tls-acme: "true"
  name: {{ include "aoi.name" . }}-grafana-ingress
  namespace: {{ $.Release.Namespace }}
spec:
  rules:
  - host: {{ include ".Values.grafana.ingress.fqdn" . }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "aoi.name" . }}-grafana
            port:
              name: service
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ include ".Values.grafana.ingress.fqdn" . }}
    secretName: {{ include "aoi.name" . }}-grafana-ingress-tls

{{- end }}
