{{- if .Values.endpointController.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kube-system
  name: {{ template "endpoint-controller.fullname" . }}
  labels: {{ include "endpoint-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  - services/finalizers
  - endpoints
  verbs:
  - get
  - create
  - update
  - delete
{{- end -}}
