{{- if .Values.endpointController.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "endpoint-controller.fullname" . }}
  labels: {{ include "endpoint-controller.labels" . | nindent 4 }}
imagePullSecrets:
{{ toYaml .Values.global.imagePullSecrets | indent 2 }}
{{- end }}
