{{- if and .Values.endpointController.enabled .Values.endpointController.windowsExporterService }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "endpoint-controller.fullname" . }}
  labels: {{ include "endpoint-controller.labels" . | nindent 4 }}
{{- if .Values.global.serviceMonitor.labels }}
{{ toYaml .Values.global.serviceMonitor.labels | indent 4}}
{{- end }}
spec:
  jobLabel: app.kubernetes.io/component
  selector:
    matchLabels:
      app.kubernetes.io/component: windows-exporter
      app.kubernetes.io/name: endpoint-controller
      app.kubernetes.io/managed-by: endpoint-controller
  namespaceSelector:
    matchNames:
      - "kube-system"
  endpoints:
  - port: http-metrics
{{- end }}
