{{- if and .Values.alertmanager.enabled .Values.alertmanager.ingress.enabled }}
{{- $serviceName := printf "%s" (include "alertmanager.fullname" .) }}
{{- $servicePort := .Values.alertmanager.service.port -}}
{{- $routePrefix := list .Values.alertmanager.alertmanagerSpec.routePrefix }}
{{- $paths := .Values.alertmanager.ingress.paths | default $routePrefix -}}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" }}
apiVersion: networking.k8s.io/v1beta1
{{ else }}
apiVersion: extensions/v1beta1
{{ end -}}
kind: Ingress
metadata:
  name: {{ $serviceName }}
{{- if .Values.alertmanager.ingress.annotations }}
  annotations:
{{ toYaml .Values.alertmanager.ingress.annotations | indent 4 }}
{{- end }}
  labels: {{ include "alertmanager.labels" . | nindent 4 }}
{{- if .Values.alertmanager.ingress.labels }}
{{ toYaml .Values.alertmanager.ingress.labels | indent 4 }}
{{- end }}
spec:
  rules:
  {{- if .Values.alertmanager.ingress.hosts }}
  {{- range $host := .Values.alertmanager.ingress.hosts }}
    - host: {{ tpl $host $ }}
      http:
        paths:
  {{- range $p := $paths }}
          - path: {{ tpl $p $ }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
  {{- end -}}
  {{- end -}}
  {{- else }}
    - http:
        paths:
  {{- range $p := $paths }}
          - path: {{ tpl $p $ }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
  {{- end -}}
  {{- end -}}
  {{- if .Values.alertmanager.ingress.tls }}
  tls:
{{ toYaml .Values.alertmanager.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
