{{- if and .Values.alertmanager.enabled .Values.alertmanager.servicePerReplica.enabled .Values.alertmanager.ingressPerReplica.enabled }}
{{- $count := .Values.alertmanager.alertmanagerSpec.replicas | int -}}
{{- $servicePort := .Values.alertmanager.service.port -}}
{{- $ingressValues := .Values.alertmanager.ingressPerReplica -}}
apiVersion: v1
kind: List
metadata:
  name: {{ include "alertmanager.fullname" $ }}-ingressperreplica
items:
{{- range $i, $e := until $count }}
  - kind: Ingress
    apiVersion: {{ include "netic-oaas.ingress.apiVersion" $ }}
    metadata:
      name: {{ include "alertmanager.fullname" $ }}-{{ $i }}
      labels: {{ include "alertmanager.labels" $ | nindent 8 }}
      {{- if $ingressValues.labels }}
      {{ toYaml $ingressValues.labels | indent 8 }}
      {{- end }}
      {{- if $ingressValues.annotations }}
      annotations:
        {{ toYaml $ingressValues.annotations | nindent 8 }}
      {{- end }}
    spec:
      rules:
        - host: {{ $ingressValues.hostPrefix }}-{{ $i }}.{{ $ingressValues.hostDomain }}
          http:
            paths:
      {{- range $p := $ingressValues.paths }}
              - path: {{ tpl $p $ }}
                {{- if and $.Values.alertmanager.ingressPerReplica.pathType (eq (include "netic-oaas.ingress.supportsPathType" $) "true") }}
                pathType: {{ $.Values.alertmanager.ingressPerReplica.pathType }}
                {{- end }}
                backend:
                {{- if eq (include "netic-oaas.ingress.isStable" $) "true" }}
                  service:
                    name: {{ include "alertmanager.fullname" $ }}-alertmanager-{{ $i }}
                    port:
                      number: {{ $servicePort }}
                  {{- else }}
                  serviceName: {{ include "alertmanager.fullname" $ }}-alertmanager-{{ $i }}
                  servicePort: {{ $servicePort }}
                {{- end }}
      {{- end -}}
      {{- if or $ingressValues.tlsSecretName $ingressValues.tlsSecretPerReplica.enabled }}
      tls:
        - hosts:
            - {{ $ingressValues.hostPrefix }}-{{ $i }}.{{ $ingressValues.hostDomain }}
          {{- if $ingressValues.tlsSecretPerReplica.enabled }}
          secretName: {{ $ingressValues.tlsSecretPerReplica.prefix }}-{{ $i }}
          {{- else }}
          secretName: {{ $ingressValues.tlsSecretName }}
          {{- end }}
      {{- end }}
{{- end -}}
{{- end -}}
