{{- if and .Values.alertmanager.enabled .Values.alertmanager.ingress.enabled }}
{{- $serviceName := printf "%s" (include "alertmanager.fullname" .) }}
{{- $servicePort := .Values.alertmanager.service.port -}}
{{- $routePrefix := list .Values.alertmanager.alertmanagerSpec.routePrefix }}
{{- $paths := .Values.alertmanager.ingress.paths | default $routePrefix -}}
apiVersion: {{ include "netic-oaas.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ $serviceName }}
{{- if .Values.alertmanager.ingress.annotations }}
  annotations:
{{ toYaml .Values.alertmanager.ingress.annotations | indent 4 }}
{{- end }}
  labels: {{ include "alertmanager.labels" . | nindent 4 }}
{{- if .Values.alertmanager.ingress.labels }}
{{ toYaml .Values.alertmanager.ingress.labels | indent 4 }}
{{- end }}
spec:
  rules:
  {{- if .Values.alertmanager.ingress.hosts }}
  {{- range $host := .Values.alertmanager.ingress.hosts }}
    - host: {{ tpl $host $ }}
      http:
        paths:
  {{- range $p := $paths }}
          - path: {{ tpl $p $ }}
            {{- if and $.Values.alertmanager.ingress.pathType (eq (include "netic-oaas.ingress.supportsPathType" $) "true") }}
            pathType: {{ $.Values.alertmanager.ingress.pathType }}
            {{- end }}
            backend:
            {{- if eq (include "netic-oaas.ingress.isStable" $) "true" }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
            {{- end }}
  {{- end -}}
  {{- end -}}
  {{- else }}
    - http:
        paths:
  {{- range $p := $paths }}
          - path: {{ tpl $p $ }}
            {{- if and $.Values.alertmanager.ingress.pathType (eq (include "netic-oaas.ingress.supportsPathType" $) "true") }}
            pathType: {{ $.Values.alertmanager.ingress.pathType }}
            {{- end }}
            backend:
            {{- if eq (include "netic-oaas.ingress.isStable" $) "true" }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
            {{- end }}
  {{- end -}}
  {{- end -}}
  {{- if .Values.alertmanager.ingress.tls }}
  tls:
{{ toYaml .Values.alertmanager.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
