{{- if and .Values.alertmanager.enabled .Values.global.rbac.create .Values.global.rbac.pspEnabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "alertmanager.fullname" . }}
  labels: {{ include "alertmanager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "alertmanager.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "alertmanager.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
