{{- if and (.Values.alertmanager.enabled) (not .Values.alertmanager.alertmanagerSpec.useExistingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-{{ template "alertmanager.fullname" . }}
{{- if .Values.alertmanager.secret.annotations }}
  annotations:
{{ toYaml .Values.alertmanager.secret.annotations | indent 4 }}
{{- end }}
  labels: {{ include "alertmanager.labels" . | nindent 4 }}
data:
{{- if .Values.alertmanager.tplConfig }}
  alertmanager.yaml: {{ tpl (toYaml .Values.alertmanager.config) . | b64enc | quote }}
{{- else }}
  alertmanager.yaml: {{ toYaml .Values.alertmanager.config | b64enc | quote }}
{{- end}}
{{- range $key, $val := .Values.alertmanager.templateFiles }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end }}
{{- end }}
