{{- if and .Values.alertmanager.enabled .Values.alertmanager.servicePerReplica.enabled }}
{{- $count := .Values.alertmanager.alertmanagerSpec.replicas | int -}}
{{- $serviceValues := .Values.alertmanager.servicePerReplica -}}
apiVersion: v1
kind: List
metadata:
  name: {{ template "alertmanager.fullname" . }}-serviceperreplica
items:
{{- range $i, $e := until $count }}
  - apiVersion: v1
    kind: Service
    metadata:
      name: {{ template "alertmanager.fullname" $ }}-{{ $i }}
      labels: {{ include "alertmanager.labels" $ | nindent 8 }}
      {{- if $serviceValues.annotations }}
      annotations:
        {{- toYaml $serviceValues.annotations | nindent 8 }}
      {{- end }}
    spec:
      {{- if $serviceValues.clusterIP }}
      clusterIP: {{ $serviceValues.clusterIP }}
      {{- end }}
      {{- if $serviceValues.loadBalancerSourceRanges }}
      loadBalancerSourceRanges:
      {{- range $cidr := $serviceValues.loadBalancerSourceRanges }}
        - {{ $cidr }}
      {{- end }}
      {{- end }}
      ports:
        - name: {{ $.Values.alertmanager.alertmanagerSpec.portName }}
          {{- if eq $serviceValues.type "NodePort" }}
          nodePort: {{ $serviceValues.nodePort }}
          {{- end }}
          port: {{ $serviceValues.port }}
          targetPort: {{ $serviceValues.targetPort }}
      selector:
        {{ include "alertmanager.matchLabels" $ | nindent 8 }}
        statefulset.kubernetes.io/pod-name: alertmanager-{{ template "alertmanager.fullname" $ }}-{{ $i }}
      type: "{{ $serviceValues.type }}"
{{- end }}
{{- end }}
