{{- if and .Values.alertmanager.enabled .Values.alertmanager.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "alertmanager.serviceAccountName" . }}
  labels: {{ include "alertmanager.labels" . | nindent 4 }}
{{- if .Values.alertmanager.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.alertmanager.serviceAccount.annotations | indent 4 }}
{{- end }}
imagePullSecrets:
{{ toYaml .Values.global.imagePullSecrets | indent 2 }}
{{- end }}
