apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "promtail-forwarding.opentelemetry-configname" . }}
  namespace: {{ include "promtail-forwarding.namespace" . }}
data:
  relay: |
    {{- tpl .Values.collectorConfig . | nindent 4 }}
