{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "opentelemetry-operator.serviceAccountName" . }}
  labels: {{ include "opentelemetry-operator.labels" . | indent 4 }}
{{- if .Values.prometheus.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.prometheus.serviceAccount.annotations | indent 4 }}
{{- end }}
imagePullSecrets:
{{ toYaml .Values.global.imagePullSecrets | indent 2 }}
{{- end }}.
