{{- if .Values.opentelemetryOperator.enabled }}
{{- if .Values.opentelemetryOperator.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "opentelemetry-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "opentelemetry-operator.labels" . | nindent 4 }}
{{- if .Values.opentelemetryOperator.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.opentelemetryOperator.serviceAccount.annotations | indent 4 }}
{{- end }}
imagePullSecrets:
{{ toYaml .Values.global.imagePullSecrets | indent 2 }}
{{- end }}
{{- end }}
