apiVersion: v1
kind: Service
metadata:
  name: {{ template "prometheus.fullname" . }}
  labels: {{ include "prometheus.labels" . | nindent 4 }}
spec:
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector: {{ include "prometheus.matchLabels" . | nindent 4 }}
  type: ClusterIP
