---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "aoi.prometheusFullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "aoi.prometheusFullname" . }}
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: {{ .Release.Namespace }}
