{{- if and .Values.kubeProxy.enabled .Values.kubeProxy.endpoints }}
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ template "kube-proxy.fullname" . }}
  labels: {{ include "kube-proxy.labels" . | nindent 4 }}
  namespace: kube-system
subsets:
  - addresses:
      {{- range .Values.kubeProxy.endpoints }}
      - ip: {{ . }}
      {{- end }}
    ports:
      - name: http-metrics
        port: {{ .Values.kubeProxy.service.port }}
        protocol: TCP
{{- end }}
