{{- if .Values.kubeProxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "kube-proxy.fullname" . }}
  labels: {{ include "kube-proxy.labels" . | nindent 4 }}
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: {{ .Values.kubeProxy.service.port }}
      protocol: TCP
      targetPort: {{ .Values.kubeProxy.service.targetPort }}
{{- if .Values.kubeProxy.endpoints }}{{- else }}
  selector:
    {{- if .Values.kubeProxy.service.selector }}
{{ toYaml .Values.kubeProxy.service.selector | indent 4 }}
    {{- else}}
    k8s-app: kube-proxy
    {{- end}}
{{- end }}
  type: ClusterIP
{{- end -}}
