{{- if .Values.authProxy.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aoi.authProxyFullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "aoi.authProxyLabels" . | nindent 4 }}
  annotations:
    {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.authProxy.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.authProxy.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  revisionHistoryLimit: {{ .Values.global.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "aoi.authProxySelectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.global.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.authProxy.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "aoi.authProxySelectorLabels" . | nindent 8 }}
        {{- with .Values.global.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.authProxy.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.authProxy.selectorLabels }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- include "aoi.authProxyPriorityClassName" . | nindent 6 }}
      securityContext:
        {{- toYaml .Values.authProxy.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.authProxy.terminationGracePeriodSeconds }}
      containers:
        - name: proxy
          image: "{{ .Values.authProxy.image.registry }}/{{ .Values.authProxy.image.repository }}:{{ .Values.authProxy.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          args:
            - --upstream={{ include "aoi.upstreamUrl" . }}
            {{- with .Values.authProxy.extraArgs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- with .Values.authProxy.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.authProxy.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.global.containerSecurityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.authProxy.resources | nindent 12 }}
      {{- with .Values.authProxy.affinity }}
      affinity:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      {{- with .Values.authProxy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.authProxy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
