{{- $namespace := printf "%s" (.Release.Namespace) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels: {{ include "labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{ include "matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "labels" . | nindent 8 }}
      {{- if .Values.prometheusOperator.podLabels }}
{{ toYaml .Values.prometheusOperator.podLabels | indent 8 }}
      {{- end }}
      {{- if .Values.prometheusOperator.podAnnotations }}
      annotations:
{{ toYaml .Values.prometheusOperator.podAnnotations | indent 8 }}
      {{- end }}
    spec:
    {{- if .Values.prometheusOperator.priorityClassName }}
      priorityClassName: {{ .Values.prometheusOperator.priorityClassName }}
    {{- end }}
      containers:
        - name: {{ template "name" . }}
          {{- if .Values.prometheusOperator.image.sha }}
          image: "{{ .Values.prometheusOperator.image.repository }}:{{ include "imageTag" . }}@sha256:{{ .Values.prometheusOperator.image.sha }}"
          {{- else }}
          image: "{{ .Values.prometheusOperator.image.repository }}:{{ include "imageTag" . }}"
          {{- end }}
          imagePullPolicy: "{{ .Values.prometheusOperator.image.pullPolicy }}"
          args:
          {{- if .Values.prometheusOperator.kubeletService.enabled }}
            - --kubelet-service={{ .Values.prometheusOperator.kubeletService.namespace }}/{{ template "fullname" . }}-kubelet
          {{- end }}
          {{- if .Values.prometheusOperator.logFormat }}
            - --log-format={{ .Values.prometheusOperator.logFormat }}
          {{- end }}
          {{- if .Values.prometheusOperator.logLevel }}
            - --log-level={{ .Values.prometheusOperator.logLevel }}
          {{- end }}
          {{- if .Values.prometheusOperator.denyNamespaces }}
            - --deny-namespaces={{ .Values.prometheusOperator.denyNamespaces | join "," }}
          {{- end }}
          {{- with $.Values.prometheusOperator.namespaces }}
          {{ $ns := .additional }}
          {{- if .releaseNamespace }}
          {{- $ns = append $ns $namespace }}
          {{- end }}
            - --namespaces={{ $ns | join "," }}
          {{- end }}
          {{- if .Values.prometheusOperator.prometheusConfigReloaderImage.sha }}
            - --prometheus-config-reloader={{ .Values.prometheusOperator.prometheusConfigReloaderImage.repository }}:{{ include "prometheusConfigReloaderImage.imageTag" . }}@sha256:{{ .Values.prometheusOperator.prometheusConfigReloaderImage.sha }}
          {{- else }}
            - --prometheus-config-reloader={{ .Values.prometheusOperator.prometheusConfigReloaderImage.repository }}:{{ include "prometheusConfigReloaderImage.imageTag" . }}
          {{- end }}
            - --config-reloader-cpu-request={{ .Values.prometheusOperator.configReloaderCpu }}
            - --config-reloader-cpu-limit={{ .Values.prometheusOperator.configReloaderCpu }}
            - --config-reloader-memory-request={{ .Values.prometheusOperator.configReloaderMemory }}
            - --config-reloader-memory-limit={{ .Values.prometheusOperator.configReloaderMemory }}
          ports:
            - containerPort: 8080
              name: http
          resources:
{{ toYaml .Values.prometheusOperator.resources | indent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ['ALL']
{{- if .Values.prometheusOperator.securityContext }}
      securityContext:
{{ toYaml .Values.prometheusOperator.securityContext | indent 8 }}
{{- end }}
      serviceAccountName: {{ template "prometheus-operator.serviceAccountName" . }}
{{- if .Values.prometheusOperator.hostNetwork }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
{{- end }}
    {{- with .Values.prometheusOperator.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.prometheusOperator.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.prometheusOperator.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
