{{- if .Values.global.tsdb.high_availability.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aoi.promxyFullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "aoi.promxyLabels" . | nindent 4 }}
  annotations:
    {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.promxy.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.promxy.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  revisionHistoryLimit: {{ .Values.global.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "aoi.promxySelectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.global.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.promxy.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "aoi.promxySelectorLabels" . | nindent 8 }}
        {{- with .Values.global.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.promxy.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.promxy.selectorLabels }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- include "aoi.promxyPriorityClassName" . | nindent 6 }}
      securityContext:
        {{- toYaml .Values.promxy.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.promxy.terminationGracePeriodSeconds }}
      containers:
        - name: proxy
          image: "{{ .Values.promxy.image.registry }}/{{ .Values.promxy.image.repository }}:{{ .Values.promxy.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          args:
            - --config=/etc/promxy/config.yaml
            - --log-level=info
            {{- with .Values.promxy.extraArgs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          command:
            - /bin/promxy
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /-/healthy
              port: http
              scheme: HTTP
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          readinessProbe:
            failureThreshold: 120
            httpGet:
              path: /-/ready
              port: http
              scheme: HTTP
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          ports:
            - name: http
              containerPort: 8082
              protocol: TCP
          volumeMounts:
            - mountPath: "/etc/promxy/"
              name: aoi-promxy-config
              readOnly: true
          {{- with .Values.promxy.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.promxy.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.global.containerSecurityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.promxy.resources | nindent 12 }}
      {{- with .Values.promxy.affinity }}
      affinity:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      {{- with .Values.promxy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.promxy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - configMap:
            name: aoi-promxy-config
          name: aoi-promxy-config
{{- end }}
