{{- if .Values.global.tsdb.high_availability.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aoi.promxyFullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "aoi.promxyLabels" . | nindent 4 }}
    {{- with .Values.global.serviceLabels }}
    {{- toYaml . | nindent 4}}
    {{- end }}
    {{- with .Values.promxy.service.labels }}
    {{- toYaml . | nindent 4}}
    {{- end }}
  annotations:
    {{- with .Values.global.serviceAnnotations }}
    {{- toYaml . | nindent 4}}
    {{- end }}
    {{- with .Values.promxy.service.annotations }}
    {{- toYaml . | nindent 4}}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8082
      targetPort: http
      protocol: TCP
  selector:
    {{- include "aoi.promxySelectorLabels" . | nindent 4 }}
{{- end }}