apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ template "netic-oaas.fullname" . }}-etcd-alerts
  labels:
    app.kubernetes.io/component: prometheus
{{ include "netic-oaas.labels" . | indent 4 }}
spec:
{{- .Files.Get "files/alerts-etcd.yaml" | nindent 2 }}
