{{- if .Values.prometheus.ingress.enabled }}
{{- $serviceName := printf "%s-%s" (include "netic-oaas.fullname" .) "prometheus" }}
{{- $servicePort := .Values.prometheus.service.port -}}
{{- $routePrefix := list .Values.prometheus.prometheusSpec.routePrefix }}
{{- $paths := .Values.prometheus.ingress.paths | default $routePrefix -}}
apiVersion: {{ include "netic-oaas.ingress.apiVersion" . }}
kind: Ingress
metadata:
{{- if .Values.prometheus.ingress.annotations }}
  annotations:
{{ toYaml .Values.prometheus.ingress.annotations | indent 4 }}
{{- end }}
  name: {{ $serviceName }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "prometheus.labels" . | nindent 4 }}
{{- if .Values.prometheus.ingress.labels }}
{{ toYaml .Values.prometheus.ingress.labels | indent 4 }}
{{- end }}
spec:
  rules:
  {{- if .Values.prometheus.ingress.hosts }}
  {{- range $host := .Values.prometheus.ingress.hosts }}
    - host: {{ tpl $host $ }}
      http:
        paths:
  {{- range $p := $paths }}
          - path: {{ tpl $p $ }}
            {{- if and $.Values.prometheus.ingress.pathType (eq (include "netic-oaas.ingress.supportsPathType" $) "true") }}
            pathType: {{ $.Values.prometheus.ingress.pathType }}
            {{- end }}
            backend:
            {{- if eq (include "netic-oaas.ingress.isStable" $) "true" }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
            {{- end }}
  {{- end -}}
  {{- end -}}
  {{- else }}
    - http:
        paths:
  {{- range $p := $paths }}
          - path: {{ tpl $p $ }}
            {{- if and $.Values.prometheus.ingress.pathType (eq (include "netic-oaas.ingress.supportsPathType" $) "true") }}
            pathType: {{ $.Values.prometheus.ingress.pathType }}
            {{- end }}
            backend:
            {{- if eq (include "netic-oaas.ingress.isStable" $) "true" }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
            {{- end }}
  {{- end -}}
  {{- end -}}
  {{- if .Values.prometheus.ingress.tls }}
  tls:
{{ toYaml .Values.prometheus.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
