{{- if .Values.global.networkPolicyEnabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "prometheus.fullname" . }}
  labels: {{ include "prometheus.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels: {{ include "prometheus.matchLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - protocol: TCP
      port: 9090
  egress:
  - {}
{{- end }}
