{{- if .Values.prometheus.podDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "netic-oaas.fullname" . }}-prometheus
  labels:
    app.kubernetes.io/component: prometheus
{{ include "netic-oaas.labels" . | indent 4 }}
spec:
  {{- if .Values.prometheus.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.prometheus.podDisruptionBudget.minAvailable }}
  {{- end  }}
  {{- if .Values.prometheus.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.prometheus.podDisruptionBudget.maxUnavailable }}
  {{- end  }}
  selector:
    matchLabels: {{ include "netic-oaas.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: prometheus
{{- end }}
