{{- if and .Values.global.rbac.create .Values.global.rbac.pspEnabled }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "prometheus.fullname" . }}-psp
  labels: {{ include "prometheus.labels" . | nindent 4 }}
rules:
{{- if semverCompare "> 1.15.0-0" (include "netic-oaas.kubeVersion" .) }}
- apiGroups: ['policy']
{{- else }}
- apiGroups: ['extensions']
{{- end }}
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - {{ template "prometheus.fullname" . }}
{{- end }}
