{{- if .Values.prometheus.serviceMonitor.selfMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "prometheus.fullname" . }}
  labels: {{ include "prometheus.labels" . | nindent 4 }}
{{- if .Values.global.serviceMonitor.labels }}
{{ toYaml .Values.global.serviceMonitor.labels | indent 4}}
{{- end }}
spec:
  selector:
    matchLabels: {{ include "prometheus.matchLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
  endpoints:
  - port: {{ .Values.prometheus.prometheusSpec.portName }}
    {{- if .Values.prometheus.serviceMonitor.interval }}
    interval: {{ .Values.prometheus.serviceMonitor.interval }}
    {{- end }}
    {{- if .Values.prometheus.serviceMonitor.scheme }}
    scheme: {{ .Values.prometheus.serviceMonitor.scheme }}
    {{- end }}
    {{- if .Values.prometheus.serviceMonitor.tlsConfig }}
    tlsConfig: {{ toYaml .Values.prometheus.serviceMonitor.tlsConfig | nindent 6 }}
    {{- end }}
    {{- if .Values.prometheus.serviceMonitor.bearerTokenFile }}
    bearerTokenFile: {{ .Values.prometheus.serviceMonitor.bearerTokenFile }}
    {{- end }}
    path: "{{ trimSuffix "/" .Values.prometheus.prometheusSpec.routePrefix }}/metrics"
{{- if .Values.prometheus.serviceMonitor.metricRelabelings }}
    metricRelabelings:
{{ tpl (toYaml .Values.prometheus.serviceMonitor.metricRelabelings | indent 6) . }}
{{- end }}
{{- if .Values.prometheus.serviceMonitor.relabelings }}
    relabelings:
{{ toYaml .Values.prometheus.serviceMonitor.relabelings | indent 6 }}
{{- end }}
{{- end }}
