{{- if .Values.prometheus.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "prometheus.serviceAccountName" . }}
  labels:
    app.kubernetes.io/component: prometheus
{{ include "netic-oaas.labels" . | indent 4 }}
{{- if .Values.prometheus.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.prometheus.serviceAccount.annotations | indent 4 }}
{{- end }}
imagePullSecrets:
{{ toYaml .Values.global.imagePullSecrets | indent 2 }}
{{- end }}
