{{- if and .Values.serviceAccount.create .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "prometheus-node-exporter.serviceAccountName" . }}
  namespace: {{ template "prometheus-node-exporter.namespace" . }}
  labels: {{ include "prometheus-node-exporter.labels" . | indent 4 }}
imagePullSecrets:
{{ toYaml .Values.serviceAccount.imagePullSecrets | indent 2 }}
{{- end -}}
