apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "otel-operator.servingCertName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "otel-operator.labels" . | nindent 4 }}
spec:
  dnsNames:
  - {{ include "otel-operator.webhookServiceName" . }}.{{ .Release.Namespace }}.svc
  - {{ include "otel-operator.webhookServiceName" . }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ include "otel-operator.issuerName" . }}
  secretName: {{ include "otel-operator.servingCertSecretName" . }}
