{{- if .Values.opentelemetryOperator.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "otel-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "otel-operator.labels" . | nindent 4 }}
{{- if .Values.opentelemetryOperator.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.opentelemetryOperator.serviceAccount.annotations | indent 4 }}
{{- end }}
{{- with .Values.global.imagePullSecrets }}
imagePullSecrets: {{ toYaml . | nindent 2 }}
{{- end }}
{{- end }}
