{{- if .Values.opentelemetryOperator.enabled }}
{{- if .Values.opentelemetryOperator.controllerManagerMetricsService.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
{{ include "otel-operator.labels" . | indent 4 }}
  name: {{ include "otel-operator.fullname" . }}-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
{{- if .Values.opentelemetryOperator.controllerManagerMetricsService.annotations }}
  annotations:
{{ toYaml .Values.opentelemetryOperator.controllerManagerMetricsService.annotations | indent 4 }}
{{- end }}
spec:
  ports:
  - name: https
    port: {{ .Values.opentelemetryOperator.controllerManagerMetricsService.port }}
    targetPort: https
  selector: {{ include "otel-operator.matchLabels" . | nindent 4 }}
{{- end }}
{{- if .Values.opentelemetryOperator.webhookService.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  labels: {{ include "otel-operator.labels" . | nindent 4 }}
  name: {{ include "otel-operator.fullname" . }}-webhook-service
  namespace: {{ .Release.Namespace }}
{{- if .Values.opentelemetryOperator.webhookService.annotations }}
  annotations:
{{ toYaml .Values.opentelemetryOperator.webhookService.annotations | indent 4 }}
{{- end }}
spec:
  ports:
  - port: {{ .Values.opentelemetryOperator.webhookService.port }}
    targetPort: 9443
  selector: {{ include "otel-operator.matchLabels" . | nindent 4 }}
{{- end }}
{{- end }}
