apiVersion: v1
appVersion: 1.0.1
description: A Helm chart for prometheus node-exporter
name: prometheus-node-exporter
home: https://git.netic.dk/projects/PD/repos/charts/browse
version: 1.0.0
keywords:
- node-exporter
- prometheus
- exporter
maintainers:
- name: langecode
  email: tal@netic.dk
