alertmanager:
  enabled: true

  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'null'
      routes:
      - match:
          alertname: Watchdog
        receiver: 'null'
      - match:
          severity: critical
        receiver: 'zenoss'
      - match:
          severity: warning
        receiver: 'zenoss'
    receivers:
    - name: 'null'
    - name: 'zenoss'
      webhook_configs:
      - url: http://host.docker.internal:8080/webhook
