global:
  imagePullSecrets:
  - name: regcred

endpointController:
  enabled: false
  image:
    repository: 083960843526.dkr.ecr.eu-north-1.amazonaws.com/endpoint-controller
    tag: latest
    pullPolicy: Always
  resources: {}

coreDns:
  enabled: true

# Requires adding extra parameters to etcd to avoid distributing certificates
# rancher_kubernetes_engine_config:
#   services:
#     etcd:
#       extra_args:
#         listen-metrics-urls: 'http://0.0.0.0:2381'
kubeEtcd:
  serviceMonitor:
    scheme: "http"

kubeControllerManager:
  serviceMonitor:
    https: false

kubeScheduler:
  serviceMonitor:
    https: false

prometheus-operator:
  enabled: false


prometheus:
  prometheusSpec:
    externalLabels:
      cluster: aws-rke-01
    remoteWrite: []

prometheus-node-exporter:
  tolerations:
    - effect: NoSchedule
      operator: Exists
    - effect: NoExecute
      operator: Exists

vector:
  daemonset:
    tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
    sinks:
      vector:
        type: "blackhole"
        inputs:
        - kubernetes_logs
        rawConfig: |
          print_amount = 100
