data_dir = "/tmp/oaas-vector"

[sources.in]
  type = "vector"
  address = "0.0.0.0:9000"

[sinks.out]
  inputs   = ["in"]
  type     = "console"
  encoding = "text"

[sinks.prometheus]
  inputs    = ["in"]
  type      = "prometheus"
  address   = "0.0.0.0:9091"
  default_namespace = "vector"
