apiVersion: v2
name: aoi
description: A Helm chart for Netic application operations infrastructure
type: application
version: 0.1.51
home: https://github.com/neticdk/k8s-oaas-observability
sources:
  - https://github.com/neticdk/k8s-oaas-observability
maintainers:
  - name: alex5517
    email: ash@netic.dk
  - name: mathiasfm
    email: mfm@netic.dk
dependencies:
  - name: grafana
    version: 8.15.0
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
  - name: victoria-metrics-single
    alias: victoria-metrics-single-1
    version: 0.24.3
    repository: https://victoriametrics.github.io/helm-charts/
    condition: global.tsdb.enabled
  - name: victoria-metrics-single
    alias: victoria-metrics-single-2
    version: 0.24.3
    repository: https://victoriametrics.github.io/helm-charts/
    condition: global.tsdb.high_availability.enabled
