{{- if and (index .Values "vector-agent" "enabled") (index .Values "vector-agent" "prometheusSink").enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "netic-oaas.vector.fullname" . }}
  labels:
{{ include "netic-oaas.vector.labels" . | indent 4 }}
{{- if .Values.global.serviceMonitor.labels }}
{{ toYaml .Values.global.serviceMonitor.labels | indent 4}}
{{- end }}
spec:
  selector:
    matchLabels: {{ include "netic-oaas.vector.matchLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    relabelings: {{ toYaml .Values.vectorMonitor.relabelings | nindent 4 }}
{{- with .Values.vectorMonitor.metricRelabelings }}
    metricRelabelings: {{ toYaml . | nindent 4 }}
{{- end }}
{{- end }}
