{{- if and .Values.grafana.enabled .Values.grafana.sidecar.datasources.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "netic-oaas.fullname" . }}-grafana-datasource
  labels:
    app.kubernetes.io/component: grafana
    {{ $.Values.grafana.sidecar.datasources.label }}: "1"
{{ include "netic-oaas.labels" . | indent 4 }}
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://{{ template "netic-oaas.fullname" . }}-prometheus:{{ .Values.prometheus.service.port }}/{{ trimPrefix "/" .Values.prometheus.prometheusSpec.routePrefix }}
      access: proxy
      isDefault: true
{{- end }}
