{{- if .Values.global.networkPolicyEnabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "netic-oaas.fullname" . }}-grafana
  labels:
    app.kubernetes.io/component: grafana
{{ include "netic-oaas.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: grafana
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - protocol: TCP
      port: 3000
  egress:
  - {}
{{- end }}
