{{- if .Values.opentelemetryCollector.enabled }}
{{- if or (.Values.global.rbac.create) (.Values.opentelemetryCollector.presets.kubernetesAttributes.enabled) (.Values.opentelemetryCollector.presets.kubernetesEvents.enabled) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "opentelemetryCollector.fullname" . }}
  labels: {{ include "opentelemetryCollector.labels" . | nindent 4 }}
{{- if .Values.opentelemetryCollector.annotations }}
  annotations:
{{ toYaml .Values.opentelemetryCollector.annotations | indent 4 }}
{{- end }}
rules:
  {{- if .Values.opentelemetryCollector.rbac.clusterRole.rules -}}
  {{ toYaml .Values.opentelemetryCollector.rbac.clusterRole.rules | nindent 2 -}}
  {{- end }}
  {{- if .Values.opentelemetryCollector.presets.kubernetesAttributes.enabled}}
  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch"]
  {{- end }}
  {{- if .Values.opentelemetryCollector.presets.kubernetesEvents.enabled }}
  - apiGroups: ["events.k8s.io"]
    resources: ["events"]
    verbs: ["watch", "list"]
  {{- end }}
{{- end }}
{{- end }}