{{- if .Values.opentelemetryCollector.enabled }}
{{- if or (.Values.global.rbac.create) (.Values.opentelemetryCollector.serviceAccount.create) (.Values.opentelemetryCollector.presets.kubernetesAttributes.enabled) (.Values.opentelemetryCollector.presets.kubernetesEvents.enabled) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "opentelemetryCollector.serviceAccountName" . }}
  labels: {{ include "opentelemetryCollector.labels" . | nindent 4 }}
{{- if .Values.opentelemetryCollector.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.opentelemetryCollector.serviceAccount.annotations | indent 4 }}
{{- end }}
imagePullSecrets:
{{ toYaml .Values.global.imagePullSecrets | indent 2 }}
{{- end }}
{{- end }}
