name: cd

on:
  push:
    branches:
      - main

jobs:
  publish_helm_chart:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          fetch-depth: 0

      #
      # Generated files
      #
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: "1.25.0"

      - name: Install extra tooling
        run: |
          go install github.com/google/go-jsonnet/cmd/jsonnet@latest
          go install github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb@latest
          go install github.com/norwoodj/helm-docs/cmd/helm-docs@v1.14.2

      - name: Render jsonnet rules for Netic OaaS chart
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          $GITHUB_WORKSPACE/charts/oaas-observability/scripts/update-rules.sh

      - name: Render documentation
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          helm-docs
          git update-index -q --ignore-submodules --refresh
          if ! git diff-files --quiet --ignore-submodules -- ; then
            echo Generating documentation caused a change - did you forget to run 'helm-docs' before commit?
            exit 1
          fi

      #
      # Deploy
      #
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4
        with:
          version: v3.15.3

      - name: Add dependency chart repos
        run: ./.github/scripts/helm-repos.sh
        shell: bash

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@cae68fefc6b5f367a0275617c9f83181ba54714f # v1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
